Ansible 2
Otus-DevOps-2018-11/MinchenkoAA_infra pull request #8
Opened 2019-01-30 17:23 UTC by MinchenkoAA

# Выполнено ДЗ №

 - [ +] Основное ДЗ
 - [ ] Задание со *

## В процессе сделано:
 - Один плейбук, один сценарий. Создал reddit_app.yml, шаблоны. Описал таски, handlers. Провел деплой для mongo. Описал таск на инстанс, handlers. Сделал шаблон. Деплой. Описал таск на установку reddit. Деплой.
 - Один плейбук, несколько сценариев. Создал reddit_app2.yml. Описал отдельные сценарии для mongo, инстанса, установки приложения. Пересоздал инфру, прогнал плейбук. Проверил.
 - Несколько плейбуков. Разбил reddit_app2.yml на app.yml, db.yml, deploy.yml. Создал site.yml. Пересоздал инфру, прогнал плейбук. Проверил.
 - Провижининг в Packer. Создал packer_app.yml, packer_db.yml. Изменил packer/app.json, packer/db.json. Пересоздал образы, инфру, прогнал плейбук. Проверил

## Как запустить проект:
 - ansible-playbook site.yml

## Как проверить работоспособность:
 - Перейти по ссылке http://<ip reddit_app>:9292

## PR checklist
 - [ +] Выставил label с номером домашнего задания
 - [ +] Выставил label с темой домашнего задания

2019-01-30 18:41 UTC, mrgreyves requested changes
Здравствуйте!) Проверил ваше дз. Нужно внести небольшие косметические изменения=)

2019-01-30 18:41 UTC, mrgreyves commented on ansible/app.yml
> +  hosts: app
Забыли ---

2019-01-30 18:41 UTC, mrgreyves commented on ansible/db.yml
> +    mongo_bind_ip: 0.0.0.0
Тоже забыли --- =(

2019-01-30 18:58 UTC, MinchenkoAA commented on ansible/app.yml
> +  hosts: app
Добрый день! 
Сначала я так и делал. Но так как эти файлы импортятся в site.yml, ansible ругался на синтаксис. Пришлось убрать (

2019-01-30 19:14 UTC, mrgreyves commented on ansible/app.yml
> +  hosts: app
Тогда на будущее просто имейте ввиду=)

2019-01-30 19:14 UTC, mrgreyves reviewed
UP!=)

2019-01-31 05:35 UTC, mrgreyves approved these changes
Заапрувил!=)

2019-01-31 05:41 UTC, merged